FROM node:18-alpine

WORKDIR /app

COPY front-end/package*.json ./
RUN npm ci

COPY front-end/ .

ENV VITE_API_BASE_URL=https://dazzling-grace-production-03a5.up.railway.app

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]