-- ====================================================================
-- CONFIG SEED: Migrated from hard-coded values
-- Generated: 2026-07-16T15:52:21.627Z
-- ====================================================================

INSERT INTO system_configs (config_key, config_value, value_type, category, description)
VALUES
  ('legal.data_retention_days', '3650', 'number', 'LEGAL', 'Thời hạn lưu trữ dữ liệu (ngày)'),
  ('financial.ai_auto_post_max', '5000000', 'number', 'FINANCIAL', 'Giới hạn tự động bút toán AI (VND)'),
  ('financial.ai_human_review_max', '50000000', 'number', 'FINANCIAL', 'Giới hạn cần duyệt bút toán AI (VND)'),
  ('financial.ai_cashflow_large', '100000000', 'number', 'FINANCIAL', 'Ngưỡng dòng tiền lớn (VND)'),
  ('financial.credit_limit_default', '500000000', 'number', 'FINANCIAL', 'Hạn mức tín dụng mặc định (VND)'),
  ('financial.threshold_revenue_3b', '3000000000', 'number', 'FINANCIAL', 'Ngưỡng doanh thu 3 tỷ (VND)'),
  ('tax.standard_vat_rate', '8', 'number', 'TAX', 'Thuế suất VAT chuẩn (8%)'),
  ('tax.service_vat_rate', '10', 'number', 'TAX', 'Thuế suất VAT dịch vụ (10%)'),
  ('financial.threshold_revenue_50b', '50000000000', 'number', 'FINANCIAL', 'Ngưỡng doanh thu 50 tỷ (VND)'),
  ('pricing.early_payment_discount', '0.02', 'number', 'PRICING', 'Chiết khấu thanh toán sớm (2%)'),
  ('payroll.employer_insurance_rate', '0.215', 'number', 'PAYROLL', 'Tỷ lệ BHXH người sử dụng lao động (21.5%)'),
  ('payroll.employee_insurance_rate', '0.105', 'number', 'PAYROLL', 'Tỷ lệ BHXH người lao động (10.5%)'),
  ('factoring.default_advance_rate', '0.8', 'number', 'FACTORING', 'Tỷ lệ ứng trước mặc định (80%)'),
  ('factoring.default_fee_rate', '0.01', 'number', 'FACTORING', 'Tỷ lệ phí mặc định (1%)'),
  ('accounts.cash', '1111', 'string', 'ACCOUNTS', 'TK Tiền mặt tại quỹ'),
  ('accounts.bank', '1121', 'string', 'ACCOUNTS', 'TK Tiền gửi ngân hàng'),
  ('accounts.bank_fc', '1122', 'string', 'ACCOUNTS', 'TK Tiền gửi ngoại tệ'),
  ('accounts.ar', '131', 'string', 'ACCOUNTS', 'TK Phải thu khách hàng'),
  ('accounts.ar_internal', '1368', 'string', 'ACCOUNTS', 'TK Phải thu nội bộ'),
  ('accounts.advance', '141', 'string', 'ACCOUNTS', 'TK Tạm ứng'),
  ('accounts.raw_material', '152', 'string', 'ACCOUNTS', 'TK Nguyên liệu'),
  ('accounts.wip', '154', 'string', 'ACCOUNTS', 'TK Sản phẩm dở dang'),
  ('accounts.finished_goods', '155', 'string', 'ACCOUNTS', 'TK Thành phẩm'),
  ('accounts.merchandise', '1561', 'string', 'ACCOUNTS', 'TK Hàng hóa'),
  ('accounts.tax_in', '1331', 'string', 'ACCOUNTS', 'TK Thuế GTGT được khấu trừ'),
  ('accounts.tax_out', '33311', 'string', 'ACCOUNTS', 'TK Thuế GTGT đầu ra'),
  ('accounts.ap', '331', 'string', 'ACCOUNTS', 'TK Phải trả người bán'),
  ('accounts.ap_internal', '3368', 'string', 'ACCOUNTS', 'TK Phải trả nội bộ'),
  ('accounts.payroll', '334', 'string', 'ACCOUNTS', 'TK Phải trả người lao động'),
  ('accounts.insurance', '338', 'string', 'ACCOUNTS', 'TK Phải trả bảo hiểm'),
  ('accounts.unearned_rev', '3387', 'string', 'ACCOUNTS', 'TK Doanh thu chưa thực hiện'),
  ('accounts.holdback', '1388', 'string', 'ACCOUNTS', 'TK Giữ lại'),
  ('accounts.asset_missing', '1381', 'string', 'ACCOUNTS', 'TK Tài sản thiếu hụt'),
  ('accounts.short_term_borrow', '341', 'string', 'ACCOUNTS', 'TK Vay ngắn hạn'),
  ('accounts.forex_diff', '4131', 'string', 'ACCOUNTS', 'TK Chênh lệch tỷ giá'),
  ('accounts.revenue', '5111', 'string', 'ACCOUNTS', 'TK Doanh thu bán hàng'),
  ('accounts.fin_revenue', '515', 'string', 'ACCOUNTS', 'TK Doanh thu hoạt động tài chính'),
  ('accounts.cogs', '632', 'string', 'ACCOUNTS', 'TK Giá vốn hàng bán'),
  ('accounts.fin_expense', '635', 'string', 'ACCOUNTS', 'TK Chi phí tài chính'),
  ('accounts.sales_expense', '641', 'string', 'ACCOUNTS', 'TK Chi phí bán hàng'),
  ('accounts.admin_expense', '6422', 'string', 'ACCOUNTS', 'TK Chi phí quản lý doanh nghiệp'),
  ('accounts.depreciation', '2141', 'string', 'ACCOUNTS', 'TK Hao mòn TSCĐ'),
  ('accounts.depreciation_expense', '6274', 'string', 'ACCOUNTS', 'TK Chi phí khấu hao'),
  ('accounts.material_cost', '621', 'string', 'ACCOUNTS', 'TK Chi phí nguyên liệu'),
  ('accounts.labor_cost', '622', 'string', 'ACCOUNTS', 'TK Chi phí nhân công'),
  ('accounts.overhead_cost', '627', 'string', 'ACCOUNTS', 'TK Chi phí sản xuất chung'),
  ('accounts.other_income', '711', 'string', 'ACCOUNTS', 'TK Thu nhập khác'),
  ('accounts.rebate', '521', 'string', 'ACCOUNTS', 'TK Chiết khấu thanh toán'),
  ('accounts.bad_debt_provision', '2293', 'string', 'ACCOUNTS', 'TK Dự phòng rủi ro nợ'),
  ('accounts.revenue_short', '511', 'string', 'ACCOUNTS', 'TK Doanh thu (rút gọn)'),
  ('accounts.vat_payable', '3331', 'string', 'ACCOUNTS', 'TK Thuế GTGT phải nộp'),
  ('accounts.corporate_tax_payable', '3334', 'string', 'ACCOUNTS', 'TK Thuế TNDN phải nộp'),
  ('accounts.retained_earnings', '4212', 'string', 'ACCOUNTS', 'TK Lợi nhuận sau thuế'),
  ('accounts.tax_expense', '821', 'string', 'ACCOUNTS', 'TK Chi phí thuế TNDN'),
  ('accounts.closing', '911', 'string', 'ACCOUNTS', 'TK Xác định kết quả'),
  ('accounts.other_expense', '811', 'string', 'ACCOUNTS', 'TK Chi phí khác'),
  ('accounts.prepaid_expense', '242', 'string', 'ACCOUNTS', 'TK Chi phí trả trước'),
  ('accounts.fixed_asset', '211', 'string', 'ACCOUNTS', 'TK Tài sản cố định'),
  ('accounts.accumulated_depreciation', '214', 'string', 'ACCOUNTS', 'TK Hao mòn TSCĐ (tổng)'),
  ('accounts.depreciation_expense_short', '611', 'string', 'ACCOUNTS', 'TK Chi phí khấu hao (rút gọn)'),
  ('accounts.doubtful_debt_provision', '335', 'string', 'ACCOUNTS', 'TK Dự phòng nợ khó đòi'),
  ('accounts.biological_asset', '215', 'string', 'ACCOUNTS', 'TK Tài sản sinh học'),
  ('accounts.biological_provision', '2295', 'string', 'ACCOUNTS', 'TK Dự phòng tài sản sinh học'),
  ('accounts.ap_short', '3311', 'string', 'ACCOUNTS', 'TK Phải trả người bán (rút gọn)'),
  ('accounts.logistics', '1562', 'string', 'ACCOUNTS', 'TK Chi phí logistics'),
  ('accounts.inventory', '156', 'string', 'ACCOUNTS', 'TK Hàng tồn kho'),
  ('accounts.customer_advance', '312', 'string', 'ACCOUNTS', 'TK Nhận ứng trước khách hàng'),
  ('accounts.depreciation_display', '223', 'string', 'ACCOUNTS', 'TK Khấu hao (hiển thị)'),
  ('accounts.tax_mon_bai', '3339', 'string', 'ACCOUNTS', 'TK Thuế môn bài'),
  ('accounts.treasury_stock', '419', 'string', 'ACCOUNTS', 'TK Quỹ cổ phiếu'),
  ('accounts.sales_return', '531', 'string', 'ACCOUNTS', 'TK Doanh thu bán bị trả lại'),
  ('accounts.sales_discount', '532', 'string', 'ACCOUNTS', 'TK Chiết khấu bán hàng'),
  ('voucher.storefront_prefix', 'WEB', 'string', 'VOUCHER', 'Tiền tố chứng từ bán hàng'),
  ('voucher.sale_voucher_type', 'XK', 'string', 'VOUCHER', 'Loại chứng từ xuất kho'),
  ('voucher.inbound_voucher_type', 'NK', 'string', 'VOUCHER', 'Loại chứng từ nhập kho'),
  ('voucher.closing_voucher_type', 'DauKy', 'string', 'VOUCHER', 'Loại chứng từ khóa sổ'),
  ('voucher.default_loading_status', 'pending_loading', 'string', 'VOUCHER', 'Trạng thái mặc định khi tải lên'),
  ('integration.order_ingestion_queue', 'order-ingestion', 'string', 'INTEGRATION', 'Tên queue xử lý đơn hàng'),
  ('integration.default_currency', 'VND', 'string', 'INTEGRATION', 'Đơn vị tiền tệ mặc định'),
  ('credit.frozen_status', 'Frozen', 'string', 'CREDIT', 'Trạng thái đóng băng tín dụng'),
  ('credit.approved_status', 'Approved', 'string', 'CREDIT', 'Trạng thái phê duyệt tín dụng'),
  ('workflow.default_status', 'PENDING', 'string', 'WORKFLOW', 'Trạng thái mặc định'),
  ('workflow.pending_approval_status', 'PENDING_APPROVAL', 'string', 'WORKFLOW', 'Trạng thái chờ phê duyệt');
