/**
 * Voucher Test Data Factory
 * Generates complete voucher objects with sensible defaults and partial overrides.
 */

let sequence = 1000;

/**
 * @param {Object} overrides
 * @returns {Object} mock voucher object
 */
export function createMockVoucher(overrides = {}) {
  sequence++;
  const defaults = {
    id: sequence,
    company_id: 1,
    voucher_number: `PT-${String(sequence).padStart(6, '0')}`,
    voucher_date: '2026-07-15',
    voucher_type: 'PT',
    description: 'Test voucher generated by factory',
    currency: 'VND',
    exchange_rate: 1,
    created_by: 1,
    is_posted: false,
    details: [
      { account_code: '1111', entry_type: 'DR', amount: 100000 },
      { account_code: '131', entry_type: 'CR', amount: 100000 },
    ],
  };

  return { ...defaults, ...overrides };
}

/**
 * Create a voucher with an arbitrary number of balanced DR/CR detail rows.
 * @param {number} companyId
 * @param {Object} options
 * @returns {Object} mock voucher with balanced details
 */
export function createBalancedVoucher(companyId = 1, options = {}) {
  const {
    drAmounts = [50000],
    crAmounts = [50000],
    drAccounts = ['1111'],
    crAccounts = ['131'],
    voucherType = 'PT',
  } = options;

  const drTotal = drAmounts.reduce((a, b) => a + b, 0);
  const crTotal = crAmounts.reduce((a, b) => a + b, 0);

  if (drTotal !== crTotal) {
    throw new Error(`createBalancedVoucher: DR total (${drTotal}) must equal CR total (${crTotal})`);
  }

  const details = [
    ...drAmounts.map((amount, i) => ({
      account_code: drAccounts[i % drAccounts.length],
      entry_type: 'DR',
      amount,
    })),
    ...crAmounts.map((amount, i) => ({
      account_code: crAccounts[i % crAccounts.length],
      entry_type: 'CR',
      amount,
    })),
  ];

  return createMockVoucher({
    company_id: companyId,
    voucher_type: voucherType,
    details,
    ...options.overrides,
  });
}

/**
 * Create an unbalanced voucher (for negative testing).
 */
export function createUnbalancedVoucher(companyId = 1, options = {}) {
  const {
    drTotal = 100000,
    crTotal = 90000,
    drAccount = '1111',
    crAccount = '131',
    voucherType = 'PT',
  } = options;

  return createMockVoucher({
    company_id: companyId,
    voucher_type: voucherType,
    details: [
      { account_code: drAccount, entry_type: 'DR', amount: drTotal },
      { account_code: crAccount, entry_type: 'CR', amount: crTotal },
    ],
  });
}